### ISSUE TITLE
Getting Error on Generate Audio

### ISSUE THREAD

**Issue by mgks** [JonathanFly/bark#106]
Here's the what I get:

```
Traceback (most recent call last):
  File "D:\ModelLibrary\Bark\installer_files\env\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\ModelLibrary\Bark\installer_files\env\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\ModelLibrary\Bark\installer_files\env\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "D:\ModelLibrary\Bark\installer_files\env\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\ModelLibrary\Bark\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\ModelLibrary\Bark\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\ModelLibrary\Bark\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\ModelLibrary\Bark\installer_files\env\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "D:\ModelLibrary\Bark\installer_files\env\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "D:\ModelLibrary\Bark\bark\bark_webui.py", line 761, in generate_audio_long_gradio
    ) = api.generate_audio_long_from_gradio(**kwargs)
  File "D:\ModelLibrary\Bark\bark\bark_infinity\api.py", line 1301, in generate_audio_long_from_gradio
    ) = generate_audio_long(**kwargs)
  File "D:\ModelLibrary\Bark\bark\bark_infinity\api.py", line 1422, in generate_audio_long
    audio_segments = chunk_up_text_prev(**kwargs)
  File "D:\ModelLibrary\Bark\bark\bark_infinity\api.py", line 1971, in chunk_up_text_prev
    audio_segments = text_processing.split_text(
  File "D:\ModelLibrary\Bark\bark\bark_infinity\text_processing.py", line 262, in split_text
    if split_type in split_type_to_function:
TypeError: unhashable type: 'list'
```

I even tried other GUIs for bark but facing the same problem with all of them, maybe something is wrong with my environment setup itself? Setup installs everything smoothly and GUI works great but stuck at the last step.

**Comment by zm4341** [comment]
Me too.

**Comment by JonathanFly** [comment]
Run INSTALL_BARK_INFINITY.bat once and it should update and be fixed now.

**Comment by mgks** [comment]
Working now, no issues. Thank you!

**Comment by neonarc4** [comment]
> Run INSTALL_BARK_INFINITY.bat once and it should update and be fixed now.

doesnt work i try manual install without conda      if split_type in split_type_to_function:
TypeError: unhashable type: 'list'

**Comment by neonarc4** [comment]
@JonathanFly u forget   File "X:\sad\practice\test\bark\bark_infinity\api.py", line 1341, in generate_audio_long
    quick_voice_clone = quick_clone(audio_file_as_history_prompt)
NameError: name 'quick_clone' is not defined
