### ISSUE TITLE
branch missing in howto

### ISSUE THREAD

**Issue by phail216** [JonathanFly/bark#36]
git clone -b https://github.com/JonathanFly/bark.git
--> Leads to an error

git clone -b **`main`** https://github.com/JonathanFly/bark.git
--> works

**Comment by JonathanFly** [comment]
Thank you.

I just removed the branch so it's git clone https://github.com/JonathanFly/bark.git

The original instructions were in a dev branch so they had a checkout, and I missed the -b when making it live.

Can you confirm the install worked btw? Still waiting for one full confirm.

**Comment by phail216** [comment]
For me it unfortunatly doesn't work.
I tried multiple things, but I get always stuck at the following.

```
(bark-infinity-oneclick) C:\Users\user\bark>python bark_webui.py
Traceback (most recent call last):
  File "C:\Users\user\mambaforge\envs\bark-infinity-oneclick\lib\site-packages\soundfile.py", line 161, in <module>
    import _soundfile_data  # ImportError if this doesn't exist
ModuleNotFoundError: No module named '_soundfile_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\mambaforge\envs\bark-infinity-oneclick\lib\site-packages\soundfile.py", line 171, in <module>
    _snd = _ffi.dlopen(_libname)
OSError: cannot load library 'C:\Users\user\mambaforge\envs\bark-infinity-oneclick\Library\bin\sndfile.dll': error 0x7e

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\bark\bark_webui.py", line 12, in <module>
    from bark_infinity import config
  File "C:\Users\user\bark\bark_infinity\__init__.py", line 1, in <module>
    from .api import generate_audio, text_to_semantic, semantic_to_waveform, save_as_prompt
  File "C:\Users\user\bark\bark_infinity\api.py", line 22, in <module>
    import soundfile
  File "C:\Users\user\mambaforge\envs\bark-infinity-oneclick\lib\site-packages\soundfile.py", line 192, in <module>
    _snd = _ffi.dlopen(_explicit_libname)
OSError: cannot load library 'libsndfile.dll': error 0x7e
```

**Comment by JonathanFly** [comment]
Oh man, and that's totally optional package, I should have just stuck with the basic one. 

Try this, one of them should work.

```
mamba install pysoundfile
mamba update pysoundfile
```
```
pip install soundfile
```

**Comment by phail216** [comment]
Tried everything but got the same issue :(
But maybe I am just too dumb to understand what is going on :D

```
(base) C:\Windows\System32>mamba activate bark-infinity-oneclick

(bark-infinity-oneclick) C:\Windows\System32>cd H:\AI\Text-to-Speech\bark\bark

(bark-infinity-oneclick) C:\Windows\System32>h:

(bark-infinity-oneclick) H:\AI\Text-to-Speech\bark\bark>mamba update mamba

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['mamba']

conda-forge/noarch                                  12.1MB @   4.2MB/s  3.6s
conda-forge/win-64                                  20.1MB @   4.2MB/s  6.2s

Pinned packages:
  - python 3.10.*


Transaction

  Prefix: H:\AI\Text-to-Speech\bark\mambaforge\envs\bark-infinity-oneclick

  All requested packages already installed


(bark-infinity-oneclick) H:\AI\Text-to-Speech\bark\bark>mamba install pysoundfile

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['pysoundfile']

conda-forge/win-64                                          Using cache
conda-forge/noarch                                          Using cache

Pinned packages:
  - python 3.10.*


Transaction

  Prefix: H:\AI\Text-to-Speech\bark\mambaforge\envs\bark-infinity-oneclick

  All requested packages already installed


(bark-infinity-oneclick) H:\AI\Text-to-Speech\bark\bark>mamba update pysoundfile

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['pysoundfile']

conda-forge/win-64                                          Using cache
conda-forge/noarch                                          Using cache

Pinned packages:
  - python 3.10.*


Transaction

  Prefix: H:\AI\Text-to-Speech\bark\mambaforge\envs\bark-infinity-oneclick

  All requested packages already installed


(bark-infinity-oneclick) H:\AI\Text-to-Speech\bark\bark>pip install soundfile
Requirement already satisfied: soundfile in h:\ai\text-to-speech\bark\mambaforge\envs\bark-infinity-oneclick\lib\site-packages (0.12.1)
Requirement already satisfied: cffi>=1.0 in h:\ai\text-to-speech\bark\mambaforge\envs\bark-infinity-oneclick\lib\site-packages (from soundfile) (1.15.1)
Requirement already satisfied: pycparser in h:\ai\text-to-speech\bark\mambaforge\envs\bark-infinity-oneclick\lib\site-packages (from cffi>=1.0->soundfile) (2.21)

(bark-infinity-oneclick) H:\AI\Text-to-Speech\bark\bark>mamba update ffmpeg

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['ffmpeg']

conda-forge/win-64                                          Using cache
conda-forge/noarch                                          Using cache

Pinned packages:
  - python 3.10.*


Transaction

  Prefix: H:\AI\Text-to-Speech\bark\mambaforge\envs\bark-infinity-oneclick

  Updating specs:

   - ffmpeg
   - ca-certificates
   - certifi
   - openssl


  Package                         Version  Build             Channel                 Size
-------------------------------------------------------------------------------------------
  Install:
-------------------------------------------------------------------------------------------

  + aom                             3.5.0  h63175ca_0        conda-forge/win-64      12MB
  + expat                           2.5.0  h63175ca_1        conda-forge/win-64     227kB
  + font-ttf-dejavu-sans-mono        2.37  hab24e00_0        conda-forge/noarch     397kB
  + font-ttf-inconsolata            3.000  h77eed37_0        conda-forge/noarch      97kB
  + font-ttf-source-code-pro        2.038  h77eed37_0        conda-forge/noarch     701kB
  + font-ttf-ubuntu                  0.83  hab24e00_0        conda-forge/noarch       2MB
  + fontconfig                     2.14.2  hbde0cde_0        conda-forge/win-64     190kB
  + fonts-conda-ecosystem               1  0                 conda-forge/noarch       4kB
  + fonts-conda-forge                   1  0                 conda-forge/noarch       4kB
  + libexpat                        2.5.0  h63175ca_1        conda-forge/win-64     139kB
  + openh264                        2.3.1  h63175ca_2        conda-forge/win-64     411kB
  + svt-av1                         1.4.1  h63175ca_0        conda-forge/win-64       2MB
  + x264                       1!164.3095  h8ffe710_2        conda-forge/win-64       1MB
  + x265                              3.5  h2d74725_3        conda-forge/win-64       6MB

  Upgrade:
-------------------------------------------------------------------------------------------

  - ffmpeg                          4.2.2  he774522_0        pkgs/main
  + ffmpeg                          5.1.2  gpl_h5b1d025_106  conda-forge/win-64      11MB

  Summary:

  Install: 14 packages
  Upgrade: 1 packages

  Total download: 36MB

-------------------------------------------------------------------------------------------


Confirm changes: [Y/n] y
openh264                                           410.8kB @   1.8MB/s  0.2s
font-ttf-inconsolata                                96.5kB @ 362.1kB/s  0.1s
x264                                                 1.0MB @   3.6MB/s  0.3s
svt-av1                                              2.0MB @   6.6MB/s  0.3s
fonts-conda-ecosystem                                3.7kB @  11.8kB/s  0.0s
expat                                              226.6kB @ 643.2kB/s  0.1s
x265                                                 5.5MB @  13.5MB/s  0.4s
font-ttf-ubuntu                                      2.0MB @   4.8MB/s  0.1s
font-ttf-dejavu-sans-mono                          397.4kB @ 951.6kB/s  0.1s
libexpat                                           138.7kB @ 315.4kB/s  0.0s
fonts-conda-forge                                    4.1kB @   9.2kB/s  0.0s
font-ttf-source-code-pro                           700.8kB @   1.5MB/s  0.1s
aom                                                 12.3MB @  24.5MB/s  0.5s
fontconfig                                         190.1kB @ 378.3kB/s  0.1s
ffmpeg                                              11.5MB @  19.3MB/s  0.3s

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(bark-infinity-oneclick) H:\AI\Text-to-Speech\bark\bark>pip install --upgrade pip
Requirement already satisfied: pip in h:\ai\text-to-speech\bark\mambaforge\envs\bark-infinity-oneclick\lib\site-packages (23.0.1)
Collecting pip
  Using cached pip-23.1.2-py3-none-any.whl (2.1 MB)
ERROR: To modify pip, please run the following command:
H:\AI\Text-to-Speech\bark\mambaforge\envs\bark-infinity-oneclick\python.exe -m pip install --upgrade pip

(bark-infinity-oneclick) H:\AI\Text-to-Speech\bark\bark>pip install soundfile
Requirement already satisfied: soundfile in h:\ai\text-to-speech\bark\mambaforge\envs\bark-infinity-oneclick\lib\site-packages (0.12.1)
Requirement already satisfied: cffi>=1.0 in h:\ai\text-to-speech\bark\mambaforge\envs\bark-infinity-oneclick\lib\site-packages (from soundfile) (1.15.1)
Requirement already satisfied: pycparser in h:\ai\text-to-speech\bark\mambaforge\envs\bark-infinity-oneclick\lib\site-packages (from cffi>=1.0->soundfile) (2.21)

(bark-infinity-oneclick) H:\AI\Text-to-Speech\bark\bark>H:\AI\Text-to-Speech\bark\mambaforge\envs\bark-infinity-oneclick\python.exe -m pip install --upgrade pip
Requirement already satisfied: pip in h:\ai\text-to-speech\bark\mambaforge\envs\bark-infinity-oneclick\lib\site-packages (23.0.1)
Collecting pip
  Using cached pip-23.1.2-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.0.1
    Uninstalling pip-23.0.1:
      Successfully uninstalled pip-23.0.1
Successfully installed pip-23.1.2

(bark-infinity-oneclick) H:\AI\Text-to-Speech\bark\bark>pip install soundfile
Requirement already satisfied: soundfile in h:\ai\text-to-speech\bark\mambaforge\envs\bark-infinity-oneclick\lib\site-packages (0.12.1)
Requirement already satisfied: cffi>=1.0 in h:\ai\text-to-speech\bark\mambaforge\envs\bark-infinity-oneclick\lib\site-packages (from soundfile) (1.15.1)
Requirement already satisfied: pycparser in h:\ai\text-to-speech\bark\mambaforge\envs\bark-infinity-oneclick\lib\site-packages (from cffi>=1.0->soundfile) (2.21)

(bark-infinity-oneclick) H:\AI\Text-to-Speech\bark\bark>python bark_webui.py
Traceback (most recent call last):
  File "H:\AI\Text-to-Speech\bark\mambaforge\envs\bark-infinity-oneclick\lib\site-packages\soundfile.py", line 161, in <module>
    import _soundfile_data  # ImportError if this doesn't exist
ModuleNotFoundError: No module named '_soundfile_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\AI\Text-to-Speech\bark\mambaforge\envs\bark-infinity-oneclick\lib\site-packages\soundfile.py", line 171, in <module>
    _snd = _ffi.dlopen(_libname)
OSError: cannot load library 'H:\AI\Text-to-Speech\bark\mambaforge\envs\bark-infinity-oneclick\Library\bin\sndfile.dll': error 0x7e

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\AI\Text-to-Speech\bark\bark\bark_webui.py", line 12, in <module>
    from bark_infinity import config
  File "H:\AI\Text-to-Speech\bark\bark\bark_infinity\__init__.py", line 1, in <module>
    from .api import generate_audio, text_to_semantic, semantic_to_waveform, save_as_prompt
  File "H:\AI\Text-to-Speech\bark\bark\bark_infinity\api.py", line 22, in <module>
    import soundfile
  File "H:\AI\Text-to-Speech\bark\mambaforge\envs\bark-infinity-oneclick\lib\site-packages\soundfile.py", line 192, in <module>
    _snd = _ffi.dlopen(_explicit_libname)
OSError: cannot load library 'libsndfile.dll': error 0x7e
```

**Comment by JonathanFly** [comment]
It's not just you, got a few reports. I'm going to remove the library for now it's not needed. Give me 30 minutes. And then try again.

**Comment by JonathanFly** [comment]
Try this:
```
mamba uninstall pysoundfile
pip install soundfile
```

**Comment by JonathanFly** [comment]
Soundfile is gone from the project. Has trouble installing everywhere.
