### ISSUE TITLE
Error when run "python bark_webui.py"

### ISSUE THREAD

**Issue by realcarlos** [JonathanFly/bark#48]
Traceback (most recent call last):
  File "/home/xxx/sound/bark/bark_webui.py", line 350, in <module>
    with gr.Blocks(theme=default_theme,css=bark_console_style) as demo:
  File "/home/xxx/.local/lib/python3.11/site-packages/gradio/blocks.py", line 1285, in __exit__
    self.config = self.get_config_file()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.local/lib/python3.11/site-packages/gradio/blocks.py", line 1261, in get_config_file
    "input": list(block.input_api_info()),  # type: ignore
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/anaconda3/envs/bark/lib/python3.11/site-packages/gradio_client/serializing.py", line 40, in input_api_info
    return (api_info["serialized_input"][0], api_info["serialized_input"][1])
            ~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'serialized_input'

**Comment by JonathanFly** [comment]
Looks like your own Python 3.11. Try setting up a anaconda with python=3.10. Python 3.11 is a trap for SO MANY weird compatibility things right now.
