### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by ArianaStar** [JonathanFly/bark#53]
Loading Bark models...
Loading text model from C:\Users\Ariana\.cache\suno\bark_v0\text_2.pt to cpu
Loading coarse model from C:\Users\Ariana\.cache\suno\bark_v0\coarse_2.pt to cpu
Traceback (most recent call last):
  File "C:\Users\Ariana\Desktop\Bark_App\New_Bark\bark\bark\bark_perform.py", line 128, in <module>
    main(namespace_args)
  File "C:\Users\Ariana\Desktop\Bark_App\New_Bark\bark\bark\bark_perform.py", line 95, in main
    generation.preload_models(args.text_use_gpu, args.text_use_small, args.coarse_use_gpu, args.coarse_use_small, args.fine_use_gpu, args.fine_use_small, args.codec_use_gpu, args.force_reload)
  File "C:\Users\Ariana\Desktop\Bark_App\New_Bark\bark\bark\bark_infinity\generation.py", line 888, in preload_models
    _ = load_model(
  File "C:\Users\Ariana\Desktop\Bark_App\New_Bark\bark\bark\bark_infinity\generation.py", line 781, in load_model
    model = _load_model_f(ckpt_path, device)
  File "C:\Users\Ariana\Desktop\Bark_App\New_Bark\bark\bark\bark_infinity\generation.py", line 813, in _load_model
    checkpoint = torch.load(ckpt_path, map_location=device)
  File "C:\Users\Ariana\mambaforge\envs\bark-infinity-oneclick\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\Ariana\mambaforge\envs\bark-infinity-oneclick\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by ArianaStar** [comment]
Taking the models from the suno folder in .cache and putting them in a seperate folder and allowed it to redownload/use cached versions or w/e it did fixed the issue. I say it used cached versions because there's no way my slow internet downloaded the models that quickly but something was done. ♥
