### ISSUE TITLE
WebUI won't open.

### ISSUE THREAD

**Issue by guestmaan** [JonathanFly/bark#62]
I pulled to the newest version of bark, installed the requirements using 
```pip install -r requirements-pip.txt```
and tried running the webui. However, it errors out here:
``` 
Traceback (most recent call last):
  File "/home/rlt/bark/bark_webui.py", line 5, in <module>
    import gradio as gr
  File "/home/rlt/.local/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/rlt/.local/lib/python3.10/site-packages/gradio/components.py", line 55, in <module>
    from gradio import processing_utils, utils
  File "/home/rlt/.local/lib/python3.10/site-packages/gradio/utils.py", line 38, in <module>
    import matplotlib
  File "/home/rlt/.local/lib/python3.10/site-packages/matplotlib/__init__.py", line 107, in <module>
    from collections import MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

I am using Python 3.10.6. Any advice? Same result in miniconda.

Thanks in advance.

**Comment by JonathanFly** [comment]
I didn't get a chance to update the installs and envs for the fork with cloning yet, hang on a bit. 

In the meantime, you can try uninstalling the conda or mamba gradio, and installing the pip gradio on the miniconda install. Gradio changes the API weekly so if the version is slightly different things can break.

**Comment by JonathanFly** [comment]
Try installing via pip **fairseq**, and via either **audiolm_pytorch**.

**Comment by guestmaan** [comment]
I'm using the pip method. Reinstalling gradio and installing fairseq and audiolm_pytorch didn't fix it.

**Comment by rmcc3** [comment]
Here is the fixed code:

```python
import os.path
import shutil
import urllib.request

import huggingface_hub

class HuBERTManager:
    @staticmethod
    def get_base_dir():
        # Get the directory that this script is in
        return os.path.dirname(os.path.abspath(__file__))

    @staticmethod
    def make_sure_hubert_installed():
        base_dir = HuBERTManager.get_base_dir()

        print(f"Current working directory: {os.getcwd()}")

        install_dir = os.path.join(base_dir,'hubert')
        print(f"Install dir: {install_dir}")
        os.makedirs(install_dir, exist_ok=True)

        install_file = os.path.join(install_dir, 'hubert.pt')
        download_url = 'https://dl.fbaipublicfiles.com/hubert/hubert_base_ls960.pt'
        if not os.path.isfile(install_file):
            print('Downloading HuBERT small model')
            urllib.request.urlretrieve(download_url, install_file)
            print('Downloaded HuBERT')


    @staticmethod
    def make_sure_tokenizer_installed():
        base_dir = HuBERTManager.get_base_dir()

        install_dir = os.path.join(base_dir,'hubert')
        os.makedirs(install_dir, exist_ok=True)
        install_file = os.path.join(install_dir, 'tokenizer.pth')
        repo = 'GitMylo/bark-voice-cloning'
        file = 'quantifier_hubert_base_ls960_14.pth'
        if not os.path.isfile(install_file):
            print('Downloading HuBERT custom tokenizer')
            huggingface_hub.hf_hub_download(repo, file, local_dir=install_dir, local_dir_use_symlinks=False)
            shutil.move(os.path.join(install_dir, file), install_file)
            print('Downloaded tokenizer')
```

**Comment by guestmaan** [comment]
Where do I put this?

**Comment by guestmaan** [comment]
My bad, figured it out.

**Comment by guestmaan** [comment]
After changing ```~bark/bark_infinity/hubert/hubert_manager.py``` to match rmcc3's edit, it worked. Thanks!

**Comment by JonathanFly** [comment]
Sorry folks, was in a rush and then wasn't able to make the fixes. Home now, will do the quick stuff and update.

**Comment by guestmaan** [comment]
> 

Kind of a dirty fix but I just symlinked the hubert models and it worked. Oddly enough it only sounds like the voice I cloned every other time I try to generate something.
